# This file contains values from Cookiecutter

default_context:
  project_name: "redis-streams-pubsub"
  project_description: "Redis PubSub with Streams"
  organization: "pingu1m"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "pingu1m/redis-streams-pubsub"
  email: "fgunix@gmail.com"
  version: "0.1.0"
  line_length: "120"
  create_example_template: "cli"
